# Generated by Django 4.1.1 on 2022-11-24 10:30

import datetime
from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='autre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime.now)),
                ('Episode_essentiels_de_maladie', models.TextField()),
                ('Prescription_Observations', models.TextField()),
                ('Prescripteur', models.CharField(max_length=30)),
                ('lieu', models.CharField(default='hopital', max_length=30)),
                ('fichier', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Carnet_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom', models.CharField(max_length=30)),
                ('Prenom', models.CharField(max_length=40, null=True)),
                ('Profession', models.CharField(max_length=30, null=True)),
                ('Date_de_naissance', models.DateField(default=datetime.datetime.now)),
                ('Secteur_ou_village', models.CharField(max_length=30, null=True)),
                ('sexe', models.CharField(choices=[('M', 'Masculin'), ('F', 'Feminin')], default='M', max_length=6, null=True)),
                ('photo', models.ImageField(upload_to='upload/')),
            ],
        ),
        migrations.CreateModel(
            name='familiaux',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime.now)),
                ('Tare', models.CharField(max_length=30)),
                ('Prescription_Observations', models.TextField()),
                ('Prescripteur', models.CharField(max_length=30)),
                ('lieu', models.CharField(default='hopital', max_length=30)),
                ('fichier', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='vaccinal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime.now)),
                ('Vaccin', models.CharField(max_length=30)),
                ('Prescription_Observations', models.TextField()),
                ('Prescripteur', models.CharField(max_length=30)),
                ('lieu', models.CharField(default='hopital', max_length=30)),
                ('fichier', models.FileField(upload_to='')),
            ],
        ),
    ]
