# Generated by Django 4.1.1 on 2022-12-02 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carnet', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='autre',
            new_name='ajouAutre',
        ),
    ]
