# Generated by Django 4.1.1 on 2022-11-25 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carnet', '0002_remove_carnet_user_id_carnet_user_proprietaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='carnet_user',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='carnet_user',
            name='proprietaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carnet.user'),
        ),
    ]
