# Generated by Django 4.1.1 on 2022-12-05 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carnet', '0002_rename_autre_ajouautre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofil',
            name='person',
        ),
        migrations.AddField(
            model_name='user',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='carnet.userprofil'),
        ),
    ]
