# Generated by Django 4.1.1 on 2022-11-25 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carnet', '0008_alter_carnet_user_proprietaire'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carnet_user',
            name='proprietaire',
        ),
    ]
